[mqtt]
  [mqtt.broker]
  url = "tcps://localhost:1883"

  [mqtt.message]
  size = 100
  format = "text"
  qos = 2
  retain = true
  payload = ""

  [mqtt.tls]
  mtls = true
  skiptlsver = true
  ca = "ca.crt"

[test]
pubs = 0
subs = 100
count = 100

[log]
quiet = true

[mainflux]
connections_file = "mfconn.toml"
