language: go

go:
  - 1.7

before_install:
  - sudo apt-get -qq update
    ##
    # Travis is running `go test -v ./...`
    # and this runs tests in `vendor` directory also.
    # There is a lot of problems with running these 3rd party tests
    # (missing DB conncetions for DBs we do not use, etc).
    # Best is to remove vendoring and force Travis build upon $GOPATH
    # and the testing just our current dir and Mainflux tests
    ##
  - rm -rf vendor

# Sudo is required for docker
sudo: required

# Enable docker
services:
  - docker

# In Travis, we need to bind to 127.0.0.1 in order to get a working connection. This environment variable
# tells dockertest to do that.
env:
  - DOCKERTEST_BIND_LOCALHOST=true

