[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "7.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/dereulenspiegel/coap-mux"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-coap"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.4.0"

[[constraint]]
  name = "github.com/go-zoo/bone"
  version = "1.2.0"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.3.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sony/gobreaker"
  version = "0.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.0"

[prune]
  go-tests = true
  unused-packages = true
