# This file is used to configure NATS broker.
# It used when running nats as an MQTT broker and RabbitMQ as a Message broker.
services:
  nats:
    extends:
      file: ../nats.yml
      service: broker
    container_name: mainflux-nats
    restart: on-failure
    networks:
      - mainflux-base-net
    volumes:
      - mainflux-mqtt-broker-volume:/data
    profiles:
      - nats_rabbitmq
