# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional lora-adapter and lora-redis services
# for the Mainflux platform. Since this service is optional, this file is dependent on the
# docker-compose.yml file from <project_root>/docker/. In order to run this service,
# core services, as well as the network from the core composition, should be already running.

version: "3.7"

networks:
  docker_mainflux-base-net:
    external: true

services:
  normalizer:
    image: mainflux/normalizer:latest
    container_name: mainflux-normalizer
    restart: on-failure
    depends_on:
      - nats
    environment:
      MF_NORMALIZER_LOG_LEVEL: ${MF_NORMALIZER_LOG_LEVEL}
      MF_NATS_URL: ${MF_NATS_URL}
      MF_NORMALIZER_PORT: ${MF_NORMALIZER_PORT}
    ports:
      - ${MF_NORMALIZER_PORT}:${MF_NORMALIZER_PORT}
    networks:
      - mainflux-base-net
