# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional MongoDB-reader service
# for Mainflux platform. Since these are optional, this file is dependent of docker-compose file
# from <project_root>/docker. In order to run this service, execute command:
# docker-compose -f docker/docker-compose.yml -f docker/addons/mongodb-reader/docker-compose.yml up
# from project root. MongoDB service is defined in docker/addons/mongodb-writer/docker-compose.yml.

version: "3.7"

networks:
  docker_mainflux-base-net:
    external: true

services:
  mongodb-reader:
    image: mainflux/mongodb-reader:${MF_RELEASE_TAG}
    container_name: mainflux-mongodb-reader
    restart: on-failure
    environment:
      MF_MONGO_READER_LOG_LEVEL: ${MF_MONGO_READER_LOG_LEVEL}
      MF_MONGO_READER_HTTP_HOST: ${MF_MONGO_READER_HTTP_HOST}
      MF_MONGO_READER_HTTP_PORT: ${MF_MONGO_READER_HTTP_PORT}
      MF_MONGO_READER_HTTP_SERVER_CERT: ${MF_MONGO_READER_HTTP_SERVER_CERT}
      MF_MONGO_READER_HTTP_SERVER_KEY: ${MF_MONGO_READER_HTTP_SERVER_KEY}
      MF_MONGO_HOST: ${MF_MONGO_HOST}
      MF_MONGO_PORT: ${MF_MONGO_PORT}
      MF_MONGO_NAME: ${MF_MONGO_NAME}
      MF_THINGS_AUTH_GRPC_URL: ${MF_THINGS_AUTH_GRPC_URL}
      MF_THINGS_AUTH_GRPC_TIMEOUT: ${MF_THINGS_AUTH_GRPC_TIMEOUT}
      MF_THINGS_AUTH_GRPC_CLIENT_TLS: ${MF_THINGS_AUTH_GRPC_CLIENT_TLS}
      MF_THINGS_AUTH_GRPC_CA_CERTS: ${MF_THINGS_AUTH_GRPC_CA_CERTS}
      MF_AUTH_GRPC_URL: ${MF_USERS_GRPC_URL}
      MF_AUTH_GRPC_TIMEOUT : ${MF_USERS_GRPC_TIMEOUT}
      MF_AUTH_GRPC_CLIENT_TLS: ${MF_USERS_GRPC_CLIENT_TLS}
      MF_AUTH_GRPC_CA_CERT: ${MF_USERS_GRPC_CA_CERT}
      MF_JAEGER_URL: ${MF_JAEGER_URL}
      MF_SEND_TELEMETRY: ${MF_SEND_TELEMETRY}   
      MF_MONGO_READER_INSTANCE_ID: ${MF_MONGO_READER_INSTANCE_ID}
    ports:
      - ${MF_MONGO_READER_HTTP_PORT}:${MF_MONGO_READER_HTTP_PORT}
    networks:
      - docker_mainflux-base-net
    volumes:
      - ../../ssl/certs:/etc/ssl/certs
