###
# Copyright (c) 2015-2017 Mainflux
#
# Mainflux server is licensed under an Apache license, version 2.0 license.
# All rights not explicitly granted in the Apache license, version 2.0 are reserved.
# See the included LICENSE file for more details.
###

version: "3"

services:
  ###
  # NATS
  ###
  nats:
    image: nats:latest
    container_name: mainflux-nats
    network_mode: bridge
    ports:
      - "4222:4222"
      - "8222:8222"

  ###
  # Cassandra
  ###
  cassandra:
    image: cassandra:latest
    container_name: mainflux-cassandra
    network_mode: bridge
    ports:
      - "9042:9042"
      - "9160:9160"

  ###
  # Traefik
  ###
  traefik:
    image: traefik:latest
    container_name: mainflux-traefik
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
    network_mode: bridge
    ports:
      - "3000:3000"

