###
# Copyright (c) 2015-2017 Mainflux
#
# Mainflux is licensed under an Apache license, version 2.0 license.
# All rights not explicitly granted in the Apache license, version 2.0 are reserved.
# See the included LICENSE file for more details.
###

version: "3"

services:
  nginx:
    image: nginx:1.13-alpine
    container_name: mainflux-nginx
    network_mode: bridge
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/ssl/certs/mainflux-server.crt:/etc/ssl/certs/mainflux-server.crt
      - $PWD/ssl/certs/mainflux-server.key:/etc/ssl/private/mainflux-server.key
      - $PWD/ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem
    ports:
      - "80:80"
      - "443:443"
      - "8883:8883"

  nats:
    image: nats:1.0.2
    container_name: mainflux-nats
    network_mode: bridge

  postgres:
    image: postgres:10.2-alpine
    container_name: mainflux-postgres
    network_mode: bridge
    environment:
      POSTGRES_USER: mainflux
      POSTGRES_PASSWORD: mainflux
      POSTGRES_DB: mainflux

  manager:
    image: mainflux/manager:latest
    container_name: mainflux-manager
    network_mode: bridge
    environment:
      MF_DB_HOST: postgres
      MF_MANAGER_DB: mainflux
      MF_MANAGER_PORT: 8180
      MF_MANAGER_SECRET: test-secret

  normalizer:
    image: mainflux/normalizer:latest
    container_name: mainflux-normalizer
    network_mode: bridge
    environment:
      MF_NATS_URL: "nats://nats:4222"
      MF_NORMALIZER_PORT: 8181

  http-adapter:
    image: mainflux/http:latest
    container_name: mainflux-http
    network_mode: bridge
    depends_on:
      - manager
    environment:
      MF_MANAGER_URL: "http://manager:8180"
      MF_NATS_URL: "nats://nats:4222"
      MF_HTTP_ADAPTER_PORT: 8182

  mqtt-adapter:
    image: mainflux/mqtt-adapter:latest
    container_name: mainflux-mqtt
    network_mode: bridge
    depends_on:
      - manager
    environment:
      MQTT_ADAPTER_NATS_URL: "nats://nats:4222"
      AUTH_URL: "http://manager"
      AUTH_PORT: 8180
