###
# Copyright (c) 2015-2017 Mainflux
#
# Mainflux is licensed under an Apache license, version 2.0 license.
# All rights not explicitly granted in the Apache license, version 2.0 are reserved.
# See the included LICENSE file for more details.
###

version: "3"

services:
  nginx:
    image: nginx:1.13-alpine
    container_name: mainflux-nginx
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/certs/mainflux-server.crt:/etc/ssl/certs/mainflux-server.crt
      - ./ssl/certs/mainflux-server.key:/etc/ssl/private/mainflux-server.key
      - ./ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem
    ports:
      - 80:80
      - 443:443
      - 8883:8883

  nats:
    image: nats:1.0.2
    container_name: mainflux-nats
    restart: on-failure

  users-db:
    image: postgres:10.2-alpine
    container_name: mainflux-users-db
    restart: on-failure
    environment:
      POSTGRES_USER: mainflux
      POSTGRES_PASSWORD: mainflux
      POSTGRES_DB: users

  users:
    image: mainflux/users:latest
    container_name: mainflux-users
    depends_on:
      - users-db
    expose:
      - 8180
      - 8181
    restart: on-failure
    environment:
      MF_USERS_DB_HOST: users-db
      MF_USERS_DB_PORT: 5432
      MF_USERS_DB_USER: mainflux
      MF_USERS_DB_PASS: mainflux
      MF_USERS_DB: users
      MF_USERS_HTTP_PORT: 8180
      MF_USERS_GRPC_PORT: 8181
      MF_USERS_SECRET: secret
    ports:
      - 8180:8180

  things-db:
    image: postgres:10.2-alpine
    container_name: mainflux-things-db
    restart: on-failure
    environment:
      POSTGRES_USER: mainflux
      POSTGRES_PASSWORD: mainflux
      POSTGRES_DB: things

  things:
    image: mainflux/things:latest
    container_name: mainflux-things
    depends_on:
      - things-db
      - users
    expose:
      - 8182
      - 8183
    restart: on-failure
    environment:
      MF_THINGS_DB_HOST: things-db
      MF_THINGS_DB_PORT: 5432
      MF_THINGS_DB_USER: mainflux
      MF_THINGS_DB_PASS: mainflux
      MF_THINGS_DB: things
      MF_THINGS_HTTP_PORT: 8182
      MF_THINGS_GRPC_PORT: 8183
      MF_USERS_URL: users:8181
      MF_THINGS_SECRET: secret
    ports:
      - 8182:8182

  normalizer:
    image: mainflux/normalizer:latest
    container_name: mainflux-normalizer
    restart: on-failure
    expose:
      - 8184
    environment:
      MF_NATS_URL: nats://nats:4222
      MF_NORMALIZER_PORT: 8184

  dashflux:
    image: mainflux/dashflux:latest
    container_name: mainflux-dashflux
    restart: on-failure
    ports:
      - 3000:3000

  ws-adapter:
    image: mainflux/ws:latest
    container_name: mainflux-ws
    depends_on:
      - things
    expose:
      - 8186
    restart: on-failure
    environment:
      MF_WS_ADAPTER_PORT: 8186
      MF_NATS_URL: nats://nats:4222
      MF_THINGS_URL: things:8183
    ports:
      - 8186:8186

  http-adapter:
    image: mainflux/http:latest
    container_name: mainflux-http
    depends_on:
      - things
    restart: on-failure
    expose:
      - 8185
    environment:
      MF_HTTP_ADAPTER_PORT: 8185
      MF_NATS_URL: nats://nats:4222
      MF_THINGS_URL: things:8183
    ports:
      - 8185:8185

  mqtt-adapter:
    image: mainflux/mqtt:latest
    container_name: mainflux-mqtt
    depends_on:
      - things
    restart: on-failure
    environment:
      MF_MQTT_ADAPTER_PORT: 1883
      MF_MQTT_WS_PORT: 8880
      MF_NATS_URL: nats://nats:4222
      MF_THINGS_URL: things:8183
    ports:
      - 1883:1883
      - 8880:8880
