apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clients
spec:
  replicas: 3
  selector:
    matchLabels:
      component: clients
  template:
    metadata:
      labels:
        component: clients
    spec:
      containers:
      - name: clients
        image: mainflux/clients:latest
        ports:
        - containerPort: 8182
          name: clients-http
        - containerPort: 8183
          name: clients-grpc
        env:
        - name: MF_CLIENTS_DB_HOST
          value: "mainflux-clients-postgres"
        - name: MF_CLIENTS_DB_PORT
          value: "5432"
        - name: MF_CLIENTS_HTTP_PORT
          value: "8182"
        - name: MF_CLIENTS_GRPC_PORT
          value: "8183"
        - name: MF_USERS_URL
          value: "users:8181"
        - name: MF_CLIENTS_SECRET
          value: "test-secret"
---
apiVersion: v1
kind: Service
metadata:
  name: clients
  labels:
    component: clients
spec:
  ports:
  - port: 8182
    targetPort: 8182
    protocol: TCP
    name: http
  - port: 8183
    targetPort: 8183
    protocol: TCP
    name: grpc
  selector:
    component: clients
  type: LoadBalancer
