apiVersion: apps/v1beta1 
kind: Deployment 
metadata:
  name: coap-adapter
  labels:
    component: coap-adapter 
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: coap-adapter
    spec:
      containers:
      - name: mainflux-coap
        image: mainflux/coap:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5683
          protocol: UDP
        env:
        - name: MF_CLIENTS_URL
          value: "clients:8183"
        - name: MF_NATS_URL
          value: "nats://nats:4222"
        - name:  MF_COAP_ADAPTER_PORT
          value: "5683"
---
apiVersion: v1 
kind: Service 
metadata:
  name: coap-adapter
  labels:
    component: coap-adapter 
spec:
  selector:
    component: coap-adapter
  ports:
  - port: 5683
    protocol: UDP
  type: LoadBalancer
