###
# Copyright (c) 2015-2017 Mainflux
#
# Mainflux server is licensed under an Apache license, version 2.0 license.
# All rights not explicitly granted in the Apache license, version 2.0 are reserved.
# See the included LICENSE file for more details.
###

version: "3"

services:

  ###
  # NGINX
  ###
  nginx:
    image: nginx:1.13-alpine
    container_name: mainflux-nginx
    volumes:
      - $PWD/docker/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/docker/ssl/certs/mainflux-server.crt:/etc/ssl/certs/mainflux-server.crt
      - $PWD/docker/ssl/certs/mainflux-server.key:/etc/ssl/private/mainflux-server.key
      - $PWD/docker/ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem
    network_mode: bridge
    ports:
      - "80:80"
      - "443:443"
      - "8883:8883"
    external_links:
      - mainflux-manager
      - mainflux-http
      - mainflux-mqtt
