###
# Copyright (c) 2015-2017 Mainflux
#
# Mainflux server is licensed under an Apache license, version 2.0 license.
# All rights not explicitly granted in the Apache license, version 2.0 are reserved.
# See the included LICENSE file for more details.
###

version: "3"

services:

  ###
  # Manager
  ###
  manager:
    image: mainflux/manager:latest
    container_name: mainflux-manager
    network_mode: bridge
    ports:
      - "8180:8180"
    external_links:
      - mainflux-cassandra:cassandra
    environment:
      - MANAGER_DB_CLUSTER=cassandra
      - MANAGER_DB_KEYSPACE=manager

  ###
  # Message Writer
  ###
  message-writer:
    image: mainflux/writer:latest
    container_name: mainflux-message-writer
    network_mode: bridge
    external_links:
      - mainflux-nats:nats
      - mainflux-cassandra:cassandra
    environment:
      - MESSAGE_WRITER_DB_CLUSTER=cassandra
      - MESSAGE_WRITER_DB_KEYSPACE=message_writer
      - MESSAGE_WRITER_NATS_URL=nats://nats:4222

  ###
  # MQTT Broker
  ###
  mqtt-adapter:
    image: mainflux/mqtt-adapter:latest
    container_name: mainflux-mqtt
    ports:
      - "1883:1883"
    network_mode: bridge
    depends_on:
        - manager
    external_links:
      - mainflux-nats:nats
      - mainflux-manager:manager
    environment:
      - MQTT_ADAPTER_NATS_URL=nats://nats:4222
      - AUTH_URL=http://manager
      - AUTH_PORT=8180

  ###
  # HTTP Server
  ###
  http-adapter:
    image: mainflux/http:latest
    container_name: mainflux-http
    network_mode: bridge
    depends_on:
        - manager
    ports:
      - "7070:7070"
    external_links:
      - mainflux-nats:nats
    environment:
      - HTTP_ADAPTER_NATS_URL=nats://nats:4222
