###
# Copyright (c) Mainflux
#
# Mainflux server is licensed under an Apache license, version 2.0.
# All rights not explicitly granted in the Apache license, version 2.0 are reserved.
# See the included LICENSE file for more details.
###

###
# HTTP Server
###
server:
  host: "0.0.0.0"    
  port: 7070

###
# NATS
###
nats:
  host: "nats"
  port: 4222
